### ISSUE TITLE
#[allow(non_snake_case)]

### ISSUE THREAD

**Issue by abrassel** [sjrusso8/spark-connect-rs#36]
Hi @sjrusso8 can you tell me the rationale behind exposing a camel cased API?

Seems like we should be fine just using idiomatic rust snake casing. 

On a separate note, do you have an IM channel of some kind to chat about this project? I would love to iterate more rapidly with you.

**Comment by sjrusso8** [comment]
The only rationale was to match the existing API naming so that someone who is use to using scala or python could easily use the rust client crate. No other real reason :) 

I’ll send you a message on slack.

**Comment by wvwwvwwv** [comment]
Hi! As a software developer who has experience in both spark-connect and Rust, I would prefer disallowing non_snake_cases in Rust code, because people who try to use this library are most likely knowledgeable about Rust and more comfortable with idiomatic Rust code.

**Comment by sjrusso8** [comment]
I've been thinking about it a lot and arrived at that same conclusion. Rust users would be expecting _rust_ idiomatic code, not spark code. I can work on switching these around.
