### ISSUE TITLE
Implement File Format Reader/Writer

### ISSUE THREAD

**Issue by sjrusso8** [sjrusso8/spark-connect-rs#54]
# Description

Implement the initial methods to read and write `.csv`, `.json`, `.orc`, `.parquet`, and `.text`. 

Consider creating `ConfigOpts` trait for each of those file options and have a custom struct represent the options for each of those file types. 

## Example with CSV

Create the Options and modify the opts object. The object is passed into the method.

```rust

let mut opts = CsvOptions::new()

opts.header = true;
opts.delimiter = b'|';

let df = spark.read().csv(path, opts)
```

Example of what the function signature might look like

```rust
impl DataFrameReader {
 ....
     pub fn csv<C: ConfigOpts>(path: &str, opts: Some(C))
}

**Comment by lexara-prime-ai** [comment]
@sjrusso8, I've been using these as references: [pysparkIO](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/io.html) and [Dataframe.reader.option](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrameReader.option.html#pyspark.sql.DataFrameReader.option), still going through the existing implementation in `readerwriter.rs`

**Comment by sjrusso8** [comment]
This looks great as a starting point! If you need some other references, I was pulling ideas from DataFusion [config](https://docs.rs/datafusion/latest/datafusion/common/config/index.html) for this purpose as well

In spark each dataframereader method for specific data sources has a long list of optional settings, a single rust method would look silly with all the `None`s. So offloading that logic into a `Config` struct with specific traits would be the best option.

**Comment by lexara-prime-ai** [comment]
Thanks @sjrusso8! The link you shared is really helpful, a similar approach would look really clean for sure.

**Comment by lexara-prime-ai** [comment]
@sjrusso8 I just created a pull request for the issue.
