### ISSUE TITLE
Implement createTable on Catalog

### ISSUE THREAD

**Issue by sjrusso8** [sjrusso8/spark-connect-rs#55]
# Description

Implement the method for `createTable` and `createExternalTable` on the `Catalog`. 

- [createTable](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.Catalog.createTable.html#pyspark.sql.Catalog.createTable)
- [createExternalTable](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.Catalog.createExternalTable.html#pyspark.sql.Catalog.createExternalTable)

**Comment by lexara-prime-ai** [comment]
Hi @sjrusso8, I'm currently implementing the two methods as discussed. I'm working on a branch that's synced with `upstream/main` and will sync any changes as needed. Please let me know if you have any additional considerations.

Thanks!

**Comment by sjrusso8** [comment]
@lexara-prime-ai sounds good! I’m working on adding all the missing functions.

**Comment by lexara-prime-ai** [comment]
@sjrusso8 I came across a small typo on the `insert_into` method when doing some manual testing. Didn't want to go out of scope so I thought I'd reach out first.

__Preview__
![insert_into_typo](https://github.com/user-attachments/assets/9dd591ac-4a11-4d69-b2ce-935378dd843f)
