### ISSUE TITLE
CICD: Release pipeline is broken

### ISSUE THREAD

**Issue by sjrusso8** [sjrusso8/spark-connect-rs#64]
# Description

There is an error when the `release to cargo` pipeline is ran. So I have been running it manually. 

Error run [9025621050](https://github.com/sjrusso8/spark-connect-rs/actions/runs/9025621050)

**Comment by lexara-prime-ai** [comment]
@sjrusso8 I tried looking at the run, but it looks like the logs expired (retention), so I forked it and created a new release. 
It looks like it's picking the manifest-file from the root directory so setting the `working-directory` should help.
Will run some tests to validate.

**Comment by lexara-prime-ai** [comment]
Looks like it worked.

![working_directory_directive](https://github.com/user-attachments/assets/e403c54c-b62e-4c55-8776-c8698b04d4f9)
