### ISSUE TITLE
If ExecutePlanRequest times out then client panics

### ISSUE THREAD

**Issue by GoEddie** [sjrusso8/spark-connect-rs#86]
In Spark 3.5.3 when sending the request if you have a long running request (`.write` takes over a minute or so) then the server terminates the connection but without sending any response so we don't ever get the operationId to re-attach to. 

In Spark 4.0 a response is sent while the long operation happens so it works but only because we receive the first response before the timeout.

To reproduce it do:

```
let df = spark.sql("SELECT reflect('java.lang.Thread', 'sleep', cast(160000 as long))").await?;
df.show(Some(100), None, None).await?;
```

In https://github.com/sjrusso8/spark-connect-rs/blob/188fb529fe27ddf15e0cc60e0bc7492cd80a8acb/crates/connect/src/client/mod.rs#L134 the `operationId` should be set to something you create (if it is null the server will generate one but because we don't ever receive the first response we can't re-attach to it), this is the python version:

```python
def __init__(
        self,
        request: pb2.ExecutePlanRequest,
        stub: grpc_lib.SparkConnectServiceStub,
        retrying: Callable[[], Retrying],
        metadata: Iterable[Tuple[str, str]],
    ):
        ExecutePlanResponseReattachableIterator._initialize_pool_if_necessary()
        self._request = request
        self._retrying = retrying
        if request.operation_id:
            self._operation_id = request.operation_id
        else:
            # Add operation id, if not present.
            # with operationId set by the client, the client can use it to try to reattach on error
            # even before getting the first response. If the operation in fact didn't even reach the
            # server, that will end with INVALID_HANDLE.OPERATION_NOT_FOUND error.
            self._operation_id = str(uuid.uuid4())
```

https://github.com/apache/spark/blob/e6252d6c6143f134201a17bb25978a136186cbfa/python/pyspark/sql/connect/client/reattach.py#L85C4-L102C13

I tried to set the operationId to a uuid4 which works but because the code expects the response to be valid it fails trying to unwrap on a none value and that is a bit beyond my rust skills!

**Comment by lexara-prime-ai** [comment]
@sjrusso8 this might be related to issue: [#71](https://github.com/sjrusso8/spark-connect-rs/issues/71) - that was **closed** recently.

**Comment by lexara-prime-ai** [comment]
@GoEddie looks like `use_reattachable_execute` is set to `true` by default whenever a new client is created.

```rust
pub fn new(stub: Arc<RwLock<SparkConnectServiceClient<T>>>, builder: ChannelBuilder) -> Self {
  let user_ref = builder.user_id.clone().unwrap_or("".to_string());

  SparkConnectClient {
      stub,
      builder,
      handler: ResponseHandler::default(),
      analyzer: AnalyzeHandler::default(),
      user_context: Some(spark::UserContext {
          user_id: user_ref.clone(),
          user_name: user_ref,
          extensions: vec![],
      }),
      tags: vec![],
      use_reattachable_execute: true,
  }
}

pub fn set_reattachable_execute(&mut self, setting: bool) -> Result<(), SparkError> {
    self.use_reattachable_execute = setting;
    Ok(())
}
```

* We can see both the `last_response_id` and `operation_id` in the `reattach_execute` logic .

```rust
   async fn reattach_execute(&mut self) -> Result<(), SparkError> {
        let mut client = self.stub.write().await;
        let req = spark::ReattachExecuteRequest {
            session_id: ...,
            user_context: ...,
            operation_id: self.handler.operation_id.clone().unwrap(),
            client_type: ...,
            last_response_id: self.handler.response_id.clone(),
        };
   ...
}
```

* However, the client does indeed **panic**:

![image](https://github.com/user-attachments/assets/087e00f3-e50c-4063-95c5-67068f789802)

cc: @sjrusso8

**Comment by sjrusso8** [comment]
I see what the issue is. It's all because I thought I was clever by storing the session_id and operation_id on the response handler :smile:  The handler gets reset to basically nothing whenever a new request is submitted. So it unwraps `None` and panics. 

I was able to get a patch working, but it's a little hacky. I'll get it cleaned up, and tested. 

![image](https://github.com/user-attachments/assets/115b997c-be61-40c0-a869-a5f16f31e2f6)
